### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

In [31]:
import numpy as np
from numpy import random as random

1. Create a 1D array of numbers from 0 to 9

In [5]:
a = [0,1,2,3,4,5,6,7,8,9]
np_a = np.array(a)
np_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [7]:
b = [[True, True, True], [True, True, True], [True, True, True]]
np_b = np.array(b)
np_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [68]:
np_c = np.arange(20,40)
np_c

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [70]:
np_c = np.arange(20,40)
np_c[np_c % 2 == 1] = -1
np_c


array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [15]:
d = np.array([2,3,4,5,6,7,8,9,4,1])
e = np.array([3,6,9,12,15,18,1,10,11,20])


In [19]:
np.intersect1d(d,e)

array([1, 3, 6, 9])

6.  Create a 5x5 identity matrix

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [23]:
x = np.array([10, 12, 9, 2, 20])
y = np.random.randint(10, 21,101)
z = np.ones((2,3), dtype = "int")

print(x)
print(y)
print(z)

[10 12  9  2 20]
[10 11 13 20 10 18 20 13 15 19 11 15 20 12 20 14 20 11 11 18 16 10 16 17
 14 12 10 10 12 19 18 20 16 11 19 18 12 10 18 19 15 15 12 17 18 20 13 17
 15 14 11 18 12 18 11 16 10 13 19 13 17 12 10 19 12 12 11 14 11 18 20 17
 20 14 13 14 16 16 20 12 11 15 10 19 12 17 18 20 11 17 14 20 14 20 20 12
 10 17 10 13 14]
[[1 1 1]
 [1 1 1]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [25]:
print(np.mean(x))
print(np.std(x))

10.6
5.782732917920384


In [28]:
x = np.sort(x)
x

array([ 2,  9, 10, 12, 20])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [34]:
from numpy.random import random as random 

In [35]:
f = random((10,10))
f

array([[0.42474877, 0.019312  , 0.17419392, 0.16592004, 0.25844166,
        0.47476523, 0.65328863, 0.63670508, 0.56579443, 0.87940109],
       [0.8952553 , 0.70478171, 0.84580027, 0.91255208, 0.98023882,
        0.21628718, 0.92255973, 0.31060972, 0.03494228, 0.88998431],
       [0.99017757, 0.20625092, 0.6285097 , 0.45265437, 0.78542225,
        0.34000753, 0.98065461, 0.43733809, 0.26273956, 0.00131472],
       [0.35338805, 0.94603685, 0.47867083, 0.41954511, 0.05610387,
        0.51349795, 0.48717579, 0.6805592 , 0.91249525, 0.14459335],
       [0.9689041 , 0.63011828, 0.13967949, 0.18936685, 0.51770782,
        0.10406104, 0.56673901, 0.60370405, 0.53070405, 0.82886325],
       [0.89818363, 0.2958267 , 0.09298399, 0.26301939, 0.79954992,
        0.56890568, 0.28103383, 0.78662025, 0.6716047 , 0.70275271],
       [0.60023254, 0.34047495, 0.96824736, 0.33721752, 0.14898239,
        0.38282926, 0.187469  , 0.37048665, 0.4629243 , 0.18818206],
       [0.36113973, 0.3931317 , 0.0376404

In [38]:
print(np.min(f))
print(np.max(f))

0.0013147197615840378
0.9901775693148759


10. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
g = np.arange(0,9)
g.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

11.  Generates an array [[1 2 3] [4 5 6]]

In [59]:
h = np.arange(1,7)
h.reshape(2,3)
# Please this question is not clear at all. Thank you!!!!

array([[1, 2, 3],
       [4, 5, 6]])

12. Generates an array [0 2.5 5 7.5 10]

In [51]:
i = np.linspace(0,10, 5)
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

13. Generates an 3x3 array of zeros

In [63]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

14. Create array from 0.1 to 10 with 12 elements, inclusively

In [66]:
np.linspace(0.1,10,12)

array([ 0.1,  1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1,
       10. ])

15. Create a matrix with seven columns and five rows of ten(10).

In [72]:
j = np.full((5,7), 10)
j

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

16. What is the difference between numpy and list?

a numpy array can only take one data type whilst a list can contain elements of different data types.   


17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [124]:
r = np.arange(1,51)
r[r%2 == 1] = 1
r[r%2 == 0] = 0
r

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [85]:
k = np.zeros((10,10)) 
print("k")
print(k)
n = np.eye(10)
m = k + n
print("m")
print(m)

k
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
m
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [89]:
x = np.zeros((10, 10))
x = np.diag((1,1,1,1,1,1,1,1,1,1))
x

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [92]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [93]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [94]:
a = np.array([[1,2],[3,4]])
a * 5

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [96]:
a = np.array([[1,2],[3,4]])
b = np.transpose(a)
a.dot(b)

array([[ 5, 11],
       [11, 25]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [97]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [98]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [99]:
b.dot(a)

array([[23, 34],
       [31, 46]])

Therefore AxB != BxA

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [104]:
x = np.array([[0, 1, 2], [3, 4, 5]])
x

array([[0, 1, 2],
       [3, 4, 5]])

In [111]:
a = x[0]
print('a')
print(a)
b = x[1]
print('b')
print(b)
c = x[:,1]
print('c')
print(c)
d = x[0, 2]
print('d')
print(d)

a
[0 1 2]
b
[3 4 5]
c
[1 4]
d
2
